version: '3'

services:
  apache:
    image: w3dev/apache-php-fpm:latest
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - php-fpm
    volumes:
      - .:/var/www

  php-fpm:
    image: w3dev/typo3cms-php-fpm:latest
    env_file:
      - ./.env
    depends_on:
      - mariadb
    volumes:
      - .:/var/www

  php-my-admin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    env_file:
      - ./.env
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.2.6
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
